version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: hr_pg
    environment:
      POSTGRES_DB: hr_monitor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - hr-network

  app:
    build: .
    container_name: hr_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hr_monitor
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - hr-network
    restart: on-failure

volumes:
  postgres_data:

networks:
  hr-network:
    driver: bridge